### ISSUE TITLE
"Can't find" error after manual removal

### ISSUE THREAD

**Issue by net-expertise** [go-gandi/terraform-provider-gandi#100]
Hi,

Deploying a simple record like
`resource "gandi_livedns_record" "www" {
  zone = "${gandi_livedns_domain.example_com.id}"
  name = "www"
  type = "A"
  ttl = 3600
  values = [
    "192.168.0.1"
  ]
}`

Removing manually from Gandi portal

I am getting "Error: 404: Can't find the DNS record www/A in the zone" when running 'terraform apply' once again.
'terraform refresh' throws the same error since it's in the refresh part that I am getting the error.

This is probably not expected.
It should recreate the record.

**Comment by nlewo** [comment]
I think this is the Terraform expected behavior: the resource exists in its state and its checks the state corresponds to the deployed resources before generating the diff to apply.
In your case, the state differs from deployed resources.

You could either use `terraform state rm` or `terraform taint` i guess.

**Comment by nlewo** [comment]
You could also use `terraform apply -refresh=false -replace=<>`.

**Comment by nlewo** [comment]
The go-gandi PR https://github.com/go-gandi/go-gandi/pull/63 would allow us to catch 404 error in order to fix the current wrong provider behavior.
