### ISSUE TITLE
Is this GH org endorsed or owned by the Gandi.net?

### ISSUE THREAD

**Issue by dsx** [go-gandi/terraform-provider-gandi#113]
It is not clear whether this GH org is owned or endorsed by the Gandi.net. Please clarify. Thank you!

**Comment by nlewo** [comment]
I opened [a PR](https://github.com/go-gandi/terraform-provider-gandi/pull/114) to clarify this.

To provide more detail, this project has been developed without any official interaction with Gandi by @tiramiseb and [others](https://github.com/go-gandi/terraform-provider-gandi/graphs/contributors). Since few months, I contribute (on my Gandi work hours) to this project.

Why you are interested in this information?

**Comment by dsx** [comment]
Thank you for clarifying this, @nlewo.  I'm asking because I'm considering using this code in production for a customer of mine.  Knowing who, what, where, when, and why helps estimate future support efforts.

**Comment by nlewo** [comment]
@dsx Thx for the details!

(btw, we merged the PR to make this more explicit in the readme)
