### ISSUE TITLE
gandi_domain nested blocks marked as optional, are actually required

### ISSUE THREAD

**Issue by vincecima** [go-gandi/terraform-provider-gandi#121]
Hello,

I was able to import an existing domain into my configuration by making sure I had the `owner`, `admin`, `tech` and `billing` nested blocks set with exactly the existing values. The plan and apply still showed that the values were being removed and added.

Once the import worked, I tried removing the `admin`, `tech` and `billing` blocks as the docs have them set as optional. However, when I do that; I get an API error:
```
StatusCode: 400 ; Err: admin.family: Required, admin.given: Required, admin.streetaddr: Required, admin.country: Required, admin.email: Required, admin.phone: Required, bill.family: Required, bill.given: Required, bill.streetaddr: Required, bill.country: Required, bill.email: Required, bill.phone: Required, tech.family: Required, tech.given: Required, tech.streetaddr: Required, tech.country: Required, tech.email: Required, tech.phone: Required
```

Are these blocks actually required or am I missing something?

Thanks!

**Comment by s256** [comment]
I'm seeing the same behavior. Also changing one value of the nested block leads to a replacement of the block instead of an update.
This however leads to the mentioned problem here: the fields are mandatory and are not to be removed. Hence an "update" fails too.

**Comment by nlewo** [comment]
> The plan and apply still showed that the values were being removed and added.

I tried to import a domain, and apply the state: it worked as expected. Are you sure your definition correspond to the current resource state?

However, I confirm there are some issues with the contact update.

**Comment by keyneston** [comment]
@nlewo I imported my domains and then ran `terraform apply`. It is hard to share the specific details becauser it contains personal information, but I've cleaned up the attached gist. Hopefully it reflect the situation well enough that it is still helpful. If you want uncensored details I'm happy to chat off list.

https://gist.github.com/keyneston/56e3b619fe5742ae02e39f8a818d5341

**Comment by nlewo** [comment]
@keyneston Thanks for these details! 
Could you try to explicitly specify the `extra_parameters` attributes in each contact block?
```
        extra_parameters = {
            "birth_city"               = ""
            "birth_country"            = ""
            "birth_date"               = ""
            "birth_department"         = ""
        }
```
It looks like the domain API has generated this attributes while you are not specifying it in your configuration. Terraform is then trying to update block to remove this attribute. 
If my hypothesis is correct, we could open a dedicated issue to fix this because it's not really convenient to have to specify empty attributes...

**Comment by keyneston** [comment]
Yea adding the extra params does stop terraform from doing a delete and add, but the issue of it doing a delete and add is still there if any attribute changes.

For example if I were to change my City to `"Foo Bar"` in one instance it does a full delete of the owner settings, which it can't because you can't have a domain without owner information. Then attempts to add the owner settings back in.

I've tried to play around with the source code to see if I can figure out how to get it to not `ForceNew`, but my understanding of the Terraform API is lacking.

Also yes this should all probably be moved to a different issue.

**Comment by nlewo** [comment]
I actually started working on the contact update issue: https://github.com/go-gandi/terraform-provider-gandi/pull/123

**Comment by nlewo** [comment]
This is fixed by https://github.com/go-gandi/terraform-provider-gandi/pull/123

**Comment by s256** [comment]
tested it. works :) 
Blocks are still replaced instead of updated, but that of course can be because of the GANDI API.

**Comment by nlewo** [comment]
Yep, the Gandi API doesn't allow you to update a specific attribute of a contact.

@s256 Thank you for the test :wink:
