### ISSUE TITLE
Versioning and release

### ISSUE THREAD

**Issue by taoufik07** [go-gandi/terraform-provider-gandi#71]
The project doesn't have a release/versioning system, which can cause lot of troubles every time a new commit is pushed especially that there's no tests.

I would suggest to start by releasing [go-gandi](https://github.com/go-gandi/go-gandi/) (v0.1.0) and then pin it and relase the current repo.

**Comment by nlewo** [comment]
I don't think we need to release go-gandi since it is pinned by commit ID (it would be nice to release it but i'm not sure we currently have the bandwidth to do it).

**Comment by tiramiseb** [comment]
I think we should release go-gandi at some point. @nlewo how do you think it could cause harm?

**Comment by nlewo** [comment]
I actually don't think it is required for a release of the `terraform-provider-gandi` project since the `go-gandi` dependency is pinned.

Note I'm definitely not against releasing `go-gandi`!
 
However, since we are trying to release `terraform-provider-gandi` since more than a year, i was suggesting to ignore (for now) all non-vital steps: i think it's better to have a non-perfect release rather than no release at all:)

**Comment by taoufik07** [comment]
Yes, pinning go-gandi is not required, but releasing won't take much time, we only need someone with enough permissions to do the release, I'll add the release workflow to go-gandi

**Comment by nlewo** [comment]
The go-gandi lib have been released and the Gandi Terraform provider v2.0.0 has been published!

https://registry.terraform.io/providers/go-gandi/gandi/latest

Thank you all!

**Comment by tiramiseb** [comment]
:tada:
